# Generated by Django 5.1.4 on 2025-01-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_costumer_id_subscription_costumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='costumer',
        ),
    ]
