# Generated by Django 5.1.4 on 2025-01-24 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_subscription_costumer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='django_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='list_of_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal')], default='Not Specified', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchased_plan',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Bronze', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_transaction_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
